
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: config-fantasma
data:
  LOG_LEVEL: "INFO"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-app
  namespace: config-fantasma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minha-app
  template:
    metadata:
      labels:
        app: minha-app
    spec:
      containers:
      - name: app
        image: linuxtips/config-reader-app:0.1
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: app-config
